import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=120, unique=True, verbose_name='Код источника')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('source_type', models.CharField(choices=[('fitness_club', 'Фитнес-клуб'), ('sports_school', 'Спортивная школа'), ('fitness_app', 'Фитнес-приложение'), ('generic_rest', 'Универсальный REST-источник')], max_length=40, verbose_name='Тип источника')),
                ('base_url', models.URLField(verbose_name='Базовый URL')),
                ('status_endpoint', models.CharField(default='status/', max_length=255, verbose_name='Эндпоинт статуса')),
                ('schema_endpoint', models.CharField(default='schema/', max_length=255, verbose_name='Эндпоинт схемы')),
                ('users_endpoint', models.CharField(max_length=255, verbose_name='Эндпоинт пользователей')),
                ('timeout_seconds', models.PositiveIntegerField(default=5, verbose_name='Таймаут, сек.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('mapping_config', models.JSONField(blank=True, default=dict, verbose_name='Правила mapping')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={'verbose_name': 'Источник данных', 'verbose_name_plural': 'Источники данных', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='GlobalUserProfile',
            fields=[
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Глобальный идентификатор')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('sport_type', models.CharField(blank=True, max_length=120, verbose_name='Вид спорта')),
                ('training_level', models.CharField(blank=True, max_length=120, verbose_name='Уровень подготовки')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('organization_type', models.CharField(blank=True, max_length=120, verbose_name='Тип организации')),
                ('organization_city', models.CharField(blank=True, max_length=120, verbose_name='Город организации')),
                ('open_to_offers', models.BooleanField(default=False, verbose_name='Открыт к предложениям')),
                ('consent_status', models.CharField(blank=True, max_length=40, verbose_name='Статус согласия')),
                ('visible_data_categories', models.JSONField(blank=True, default=list, verbose_name='Видимые категории данных')),
                ('allowed_organization_types', models.JSONField(blank=True, default=list, verbose_name='Разрешённые типы организаций')),
                ('source_summary', models.JSONField(blank=True, default=list, verbose_name='Сводка источников')),
                ('raw_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Последний снимок нормализованных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={'verbose_name': 'Глобальный профиль', 'verbose_name_plural': 'Глобальные профили', 'ordering': ['full_name']},
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_activity_id', models.CharField(blank=True, max_length=150, verbose_name='Локальный ID активности')),
                ('activity_date', models.DateField(blank=True, null=True, verbose_name='Дата активности')),
                ('activity_type', models.CharField(blank=True, max_length=120, verbose_name='Тип активности')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мин.')),
                ('intensity', models.CharField(blank=True, max_length=80, verbose_name='Интенсивность')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mediator.globaluserprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mediator.datasource')),
            ],
            options={'verbose_name': 'Активность', 'verbose_name_plural': 'Активности', 'ordering': ['-activity_date', 'activity_type']},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediator.globaluserprofile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediator.datasource')),
            ],
            options={'verbose_name': 'Журнал аудита', 'verbose_name_plural': 'Журнал аудита', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_to_offers', models.BooleanField(default=False, verbose_name='Открыт к предложениям')),
                ('status', models.CharField(blank=True, max_length=40, verbose_name='Статус')),
                ('visible_data_categories', models.JSONField(blank=True, default=list, verbose_name='Видимые категории')),
                ('allowed_organization_types', models.JSONField(blank=True, default=list, verbose_name='Разрешённые типы организаций')),
                ('granted_at', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='mediator.globaluserprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='mediator.datasource')),
            ],
            options={'verbose_name': 'Согласие', 'verbose_name_plural': 'Согласия', 'unique_together': {('profile', 'source')}},
        ),
        migrations.CreateModel(
            name='HealthMetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_metric_id', models.CharField(blank=True, max_length=180, verbose_name='Локальный ID показателя')),
                ('metric_type', models.CharField(max_length=120, verbose_name='Тип показателя')),
                ('metric_value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('measured_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата измерения')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='mediator.globaluserprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='mediator.datasource')),
            ],
            options={'verbose_name': 'Показатель здоровья', 'verbose_name_plural': 'Показатели здоровья', 'ordering': ['metric_type', '-measured_at']},
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=255, verbose_name='Тренер')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Организация тренера')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='mediator.globaluserprofile')),
            ],
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SourceUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_user_id', models.CharField(max_length=150, verbose_name='Локальный ID пользователя')),
                ('fingerprint', models.CharField(blank=True, max_length=255, verbose_name='Отпечаток для дедупликации')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='mediator.globaluserprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='mediator.datasource')),
            ],
            options={'verbose_name': 'Связь с локальной записью', 'verbose_name_plural': 'Связи с локальными записями', 'ordering': ['source__name', 'local_user_id'], 'unique_together': {('source', 'local_user_id')}},
        ),
    ]
